Repository delphi-hub/delphi-management, pull requests merged in 2018-05, with the labels that each got.

#16 Added a code of conduct
  CODE_OF_CONDUCT.md
Labels: review

#18 Update for the project baseline (configuration etc.)
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .gitignore
  CODE_OF_CONDUCT.md
  app/controllers/HomeController.scala
  app/views/index.scala.html
  app/views/main.scala.html
  app/views/welcome.scala.html
  build.sbt
  conf/application.conf
  conf/logback.xml
  conf/routes
  project/build.properties
  project/plugins.sbt
  public/images/favicon.png
  public/images/logo.svg
  public/scripts/bootstrap.bundle.js
  public/scripts/bootstrap.bundle.js.map
  public/scripts/bootstrap.bundle.min.js
  public/scripts/bootstrap.bundle.min.js.map
  public/scripts/bootstrap.js
  public/scripts/bootstrap.js.map
  public/scripts/bootstrap.min.js
  public/scripts/bootstrap.min.js.map
  public/stylesheets/bootstrap-grid.css
  public/stylesheets/bootstrap-grid.css.map
  public/stylesheets/bootstrap-grid.min.css
  public/stylesheets/bootstrap-grid.min.css.map
  public/stylesheets/bootstrap-reboot.css
  public/stylesheets/bootstrap-reboot.css.map
  public/stylesheets/bootstrap-reboot.min.css
  public/stylesheets/bootstrap-reboot.min.css.map
  public/stylesheets/bootstrap.css
  public/stylesheets/bootstrap.css.map
  public/stylesheets/bootstrap.min.css
  public/stylesheets/bootstrap.min.css.map
  public/stylesheets/default.css
  public/stylesheets/main.css
Labels: review

#20 Introduced user authentication using framework silhouette.
  app/controllers/AuthController.scala
  app/controllers/HomeController.scala
  app/daos/MockAdminUser.scala
  app/daos/PasswordInfoDao.scala
  app/daos/UserDao.scala
  app/models/User.scala
  app/module/Module.scala
  app/services/UserService.scala
  app/utils/ErrorHandler.scala
  app/utils/auth/DefaultEnv.scala
  app/views/auth/signIn.scala.html
  app/views/errors/alert.scala.html
  app/views/errors/notFound.scala.html
  app/views/errors/serverError.scala.html
  app/views/index.scala.html
  app/views/main.scala.html
  app/views/templates/authenticated.scala.html
  app/views/templates/notAuthenticated.scala.html
  app/views/welcome.scala.html
  build.sbt
  conf/application.conf
  conf/messages
  conf/routes
  conf/silhouette.conf
  project/plugins.sbt
  public/stylesheets/default.css
  public/stylesheets/login.css
  test/daostest/MockAdminUserTest.scala
Labels: enhancement, needed for deployment, review

#29 Added checking of code style using scalastyle
  app/controllers/AuthController.scala
  app/controllers/HomeController.scala
  app/daos/MockAdminUser.scala
  app/daos/PasswordInfoDao.scala
  app/daos/UserDao.scala
  app/models/User.scala
  app/module/Module.scala
  app/services/UserService.scala
  app/utils/ErrorHandler.scala
  conf/application.conf
  project/scalastyle_config.xml
  test/daostest/MockAdminUserTest.scala
Labels: review

#33 Reformatting of Log structure
  conf/logback.xml
Labels: review

#35 Global sbt
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: review

#34 Feat/sysinfo
  app/controllers/HomeController.scala
  app/controllers/SystemInfo.scala
  app/views/index.scala.html
  app/views/main.scala.html
  app/views/welcome.scala.html
  build.sbt
  public/stylesheets/default.css
  test/systeminfotest/SystemInfoTest.scala
Labels: review

#38 Fixed a bug preventing the navbar margin from being applied
  public/stylesheets/default.css
Labels: bug, review
