Repository delphi-hub/delphi-management, pull requests merged in 2019-01, with the labels that each got.

#90 Update api.service.ts
  client/src/app/api/api/api.service.ts
Labels: review

#89 Feature/model service
  app/controllers/ApiRouter.scala
  app/controllers/InstanceRegistryController.scala
  app/models/Event.scala
  app/models/Instance.scala
  client/package-lock.json
  client/package.json
  client/src/app/api/api/api.service.ts
  client/src/app/api/api/socket.service.ts
  client/src/app/api/model/instanceLink.ts
  client/src/app/api/model/instanceNetwork.ts
  client/src/app/api/variables.ts
  client/src/app/dashboard/add-dialog/add-dialog.component.html
  client/src/app/dashboard/add-dialog/add-dialog.component.spec.ts
  client/src/app/dashboard/add-dialog/add-dialog.component.ts
  client/src/app/dashboard/crawler/crawler.component.spec.ts
  client/src/app/dashboard/crawler/crawler.component.ts
  client/src/app/dashboard/dashboard-card/dashboard-card.component.ts
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.ts
  client/src/app/dashboard/dashboard.module.ts
  client/src/app/dashboard/delete-dialog/delete-dialog.component.html
  client/src/app/dashboard/delete-dialog/delete-dialog.component.ts
  client/src/app/dashboard/status-card/status-card.component.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/app/dashboard/webapi/web-api.component.spec.ts
  client/src/app/dashboard/webapi/web-api.component.ts
  client/src/app/dashboard/webapp/webapp.component.spec.ts
  client/src/app/dashboard/webapp/webapp.component.ts
  client/src/app/model/model.module.ts
  client/src/app/model/model.service.spec.ts
  client/src/app/model/model.service.ts
  client/src/app/model/models/instance.ts
  client/src/app/model/models/instanceLink.ts
  client/src/app/model/models/socketMessage.ts
  client/src/app/model/models/sysInfo.ts
  client/src/app/model/store.service.spec.ts
  client/src/app/model/store.service.ts
  client/src/assets/images/Elasticsearch.png
Labels: review

#93 Feature/dockerControlHide
  client/package-lock.json
  client/package.json
  client/src/app/dashboard/table-all/table-all.component.html
Labels: review

#95 Hotfix/parsing error
  .travis.yml
  README.md
  app/controllers/InstanceRegistryController.scala
  client/package-lock.json
  client/package.json
  client/src/app/api/api/api.service.ts
  client/src/app/api/api/socket.service.spec.ts
  client/src/app/dashboard/status-card/status-card.component.spec.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/app/model/model.service.ts
Labels: bug, review

#99 Feature/docker control buttons
  client/package-lock.json
  client/src/app/dashboard/add-dialog/add-dialog.component.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
Labels: review

#100 Fix of Random failing tests refs #91
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.spec.ts
Labels: review

#102 Update build.sbt
  build.sbt
Labels: review

#104 Added table expand feature to display docker ID and labels.
  client/package-lock.json
  client/src/app/dashboard/table-all/table-all.component.css
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
Labels: review

#106 Feature/cytoscape
  app/models/Event.scala
  app/models/Instance.scala
  app/models/InstanceLink.scala
  app/models/InstanceNetwork.scala
  app/models/SocketMessage.scala
  app/models/SystemInfo.scala
  build.sbt
  client/package-lock.json
  client/package.json
  client/src/app/api/api/api.service.ts
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.html
  client/src/app/dashboard/dashboard-routing.module.spec.ts
  client/src/app/dashboard/dashboard-routing.module.ts
  client/src/app/dashboard/dashboard.module.ts
  client/src/app/dashboard/graph-view/graph-view.module.ts
  client/src/app/dashboard/graph-view/graph-view.service.spec.ts
  client/src/app/dashboard/graph-view/graph-view.service.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.css
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.html
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.spec.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.ts
  client/src/app/dashboard/header/header.component.html
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/assets/images/crawler-failed.png
  client/src/assets/images/crawler-paused.png
  client/src/assets/images/crawler-running.png
  client/src/assets/images/crawler-stopped.png
  client/src/assets/images/elasticsearch-failed.png
  client/src/assets/images/elasticsearch-paused.png
  client/src/assets/images/elasticsearch-running.png
  client/src/assets/images/elasticsearch-stopped.png
  client/src/assets/images/webapi-failed.png
  client/src/assets/images/webapi-paused.png
  client/src/assets/images/webapi-running.png
  client/src/assets/images/webapi-stopped.png
  client/src/assets/images/webapp-failed.png
  client/src/assets/images/webapp-paused.png
  client/src/assets/images/webapp-running.png
  client/src/assets/images/webapp-stopped.png
Labels: enhancement, review
