Repository delphi-hub/delphi-management, pull requests merged in 2019-03, with the labels that each got.

#126 Feature/delete instance feedback
  client/src/app/dashboard/label-dialog/label-dialog.component.html
  client/src/app/dashboard/label-dialog/label-dialog.component.ts
  client/src/app/dashboard/table-all/table-all.component.ts
Labels: review

#127 Feature/user auth
  app/authorization/AuthAction.scala
  app/authorization/AuthProvider.scala
  app/controllers/ApiRouter.scala
  app/controllers/InstanceRegistryController.scala
  app/controllers/SystemInfoController.scala
  build.sbt
  client/package-lock.json
  client/package.json
  client/src/app-theme.scss
  client/src/app/AuthGuard.ts
  client/src/app/api/api/api.service.ts
  client/src/app/api/api/socket.service.spec.ts
  client/src/app/api/auth.service.ts
  client/src/app/api/variables.ts
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/dashboard/add-dialog/add-dialog.component.spec.ts
  client/src/app/dashboard/dashboard-routing.module.ts
  client/src/app/landing-page/landing-page.component.css
  client/src/app/landing-page/landing-page.component.html
  client/src/app/landing-page/landing-page.component.spec.ts
  client/src/app/landing-page/landing-page.component.ts
  client/src/app/landing-page/landing-page.module.ts
  client/src/assets/images/delphiLogo.png
Labels: review

#125 Feature/information center
  client/package-lock.json
  client/package.json
  client/src/app/api/api/socket.service.ts
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.html
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.spec.ts
  client/src/app/dashboard/dashboard.component.spec.ts
  client/src/app/dashboard/dashboard.module.ts
  client/src/app/dashboard/info-center/info-center-datasource.ts
  client/src/app/dashboard/info-center/info-center.component.css
  client/src/app/dashboard/info-center/info-center.component.html
  client/src/app/dashboard/info-center/info-center.component.spec.ts
  client/src/app/dashboard/info-center/info-center.component.ts
  client/src/app/dashboard/infor-center/infor-center.component.css
  client/src/app/dashboard/infor-center/infor-center.component.html
  client/src/app/dashboard/infor-center/infor-center.component.spec.ts
  client/src/app/dashboard/infor-center/infor-center.component.ts
Labels: review

#133 Feature/checks if user is an admin
  client/src/app/api/auth.service.ts
Labels: enhancement, review

#135 Release/0.9.5
  build.sbt
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.ts
  client/src/app/landing-page/landing-page.component.ts
Labels: review

#136 WIP: Feature/instance details
  build.sbt
  client/src/app/app.module.ts
  client/src/app/dashboard/dashboard-routing.module.ts
  client/src/app/dashboard/dashboard.module.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.spec.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.ts
  client/src/app/dashboard/info-center/info-center-datasource.ts
  client/src/app/dashboard/info-center/info-center.component.html
  client/src/app/dashboard/info-center/info-center.component.ts
  client/src/app/dashboard/instance-details/instance-details.component.html
  client/src/app/dashboard/instance-details/instance-details.component.spec.ts
  client/src/app/dashboard/instance-details/instance-details.component.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/app/dashboard/table-overview/table-overview.component.html
  client/src/app/dashboard/table-overview/table-overview.component.spec.ts
  client/src/app/dashboard/table-overview/table-overview.component.ts
  client/src/app/material-module/material.module.ts
  client/src/app/model/models/instance.ts
Labels: in progress, review

#138 Feature/event model
  app/controllers/InstanceRegistryController.scala
  client/src/app/dashboard/add-dialog/add-dialog.component.ts
  client/src/app/dashboard/graph-view/graph-view.service.ts
  client/src/app/dashboard/info-center/info-center-datasource.ts
  client/src/app/dashboard/info-center/info-center.component.html
  client/src/app/dashboard/info-center/info-center.component.ts
  client/src/app/model/event.service.spec.ts
  client/src/app/model/event.service.ts
  client/src/app/model/model.service.ts
  client/src/app/model/store.service.ts
Labels: review

#140 Upgrading vulnerable dependencies
  build.sbt
Labels: bug, infrastructure, review

#139 Added delete label feature
  app/controllers/ApiRouter.scala
  app/controllers/InstanceRegistryController.scala
  client/src/app/api/api/api.service.ts
  client/src/app/api/variables.ts
  client/src/app/dashboard/dashboard-card/dashboard-card.component.spec.ts
  client/src/app/dashboard/dashboard.module.ts
  client/src/app/dashboard/instance-details/instance-details.component.spec.ts
  client/src/app/dashboard/label-delete/label-delete.component.css
  client/src/app/dashboard/label-delete/label-delete.component.html
  client/src/app/dashboard/label-delete/label-delete.component.spec.ts
  client/src/app/dashboard/label-delete/label-delete.component.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.spec.ts
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/app/dashboard/table-overview/table-overview.component.spec.ts
  client/src/app/dashboard/user-management/user-management.component.css
  client/src/app/dashboard/user-management/user-management.component.html
Labels: review

#141 hotfix/userAccessLevel
  app/authorization/AuthAction.scala
  app/authorization/AuthProvider.scala
  app/controllers/InstanceRegistryController.scala
  client/package-lock.json
  client/package.json
  client/src/app/api/api.module.ts
  client/src/app/api/auth.service.ts
  client/src/app/dashboard/dashboard-overview/dashboard-overview.component.spec.ts
  client/src/app/dashboard/graph-view/graph-view.module.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.spec.ts
  client/src/app/dashboard/graph-view/graph-view/graph-view.component.ts
  client/src/app/dashboard/header/header.component.html
  client/src/app/dashboard/info-center/info-center-datasource.ts
  client/src/app/dashboard/table-all/table-all.component.html
  client/src/app/dashboard/table-all/table-all.component.spec.ts
  client/src/app/dashboard/table-all/table-all.component.ts
  client/src/app/dashboard/table-overview/table-overview.component.spec.ts
  client/src/app/dashboard/user-management/user-management.component.ts
  client/tsconfig.json
  conf/application.conf
Labels: review, security
